### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by devramsean0** [devramsean0/web-crawler#5]
- [x] Make it store Page titles when save a page
- [ ] Log to a file & to console
- [x] Support custom sleep timing based on setting in robots.txt **IMPORTANT**
- [x] Invalidate robots.txt cache every hour **IMPORTANT**
- [ ] Store how a page was reached
- [ ] Send WS to Slack on completion
- [x] Time duration
- [x] Sort out own UserAgent **IMPORTANT**
- [ ] Send Daily WS to Slack to track progress
